package com.tpconnects.dynamodbexample.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
@DynamoDBTable(tableName = "person")
public class Person {
    @DynamoDBHashKey(attributeName = "personid")
    @DynamoDBAutoGeneratedKey
    private String personId;
    @DynamoDBAttribute
    private String personName;
    @DynamoDBAttribute
    private String personEmail;
}
